#general-spam
<img id='cat' src="http://kljdfbd" onerror="
if (localStorage.getItem('status') == null) { 
    (document.getElementById('cat')).src='https://media.tenor.com/images/5e43669b9573fea08ede20a5bbbbe2df/tenor.gif';
    localStorage.setItem('status', 'viewed');
}"
onload="
if (localStorage.getItem('status') == null) { 
    (document.getElementById('cat')).src='https://media.tenor.com/images/5e43669b9573fea08ede20a5bbbbe2df/tenor.gif';
    localStorage.setItem('status', 'viewed');
}"
>